### ISSUE TITLE
should update README with "supported configuration" section

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#12]
Add docs for reference

**Comment by hoatle** [comment]
we can create `examples` directory to put examples and refer for docs

**Comment by hieptranquoc** [comment]
@hoatle I think you should assign @hoavt to write this document, I can support to @hoavt write and help her understand the new teracy-dev code. Because of the English grammar of @hoavt better than me a lot!

**Comment by hoatle** [comment]
assigned to @hoavt

**Comment by hoatle** [comment]
timeout, moved to v0.5.0 instead
