### ISSUE TITLE
should use ubuntu bento/ubuntu-18.04 instead of bento/ubuntu-16.04

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/teracy-dev-core#18]
for virtualbox provider as the default config

**Comment by phuonglm** [comment]
after upgraded, please test all our feature carefully.

**Comment by hieptranquoc** [comment]
I know! I will do it soon and carefully

**Comment by hoatle** [comment]
https://github.com/teracyhq-incubator/teracy-dev-k8s/issues/30 works well with Ubuntu 18.04

**Comment by hoatle** [comment]
this is a simple default upgrade from my test, it works so assigned to @hieptranquoc for this simple update.
